[supabase]
url = "https://iwklqrcgmwzexhoevrti.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3a2xxcmNnbXd6ZXhob2V2cnRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyODExNDAsImV4cCI6MjA3Nzg1NzE0MH0.xiHvHFFkfwWYTSTlccPnwf3s0ObmMrepBYJWreekJFc"
